url: https://histoires.noesya.coop
title: Histoires Noesya
subdomain: Histoire
lang: fr

exclude: ['node_modules', '_js', 'README.md']

theme: "jekyll-theme-noesya"

collections:
  pages:
    output: true
  stories:
    output: true

plugins:
  - jekyll-minifier
  - jekyll-sitemap

sass:
  style: compressed
  load_paths:
      - _sass
      - node_modules

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: false
  remove_comments: true
  compress_css: false
  compress_javascript: true

picture:
  ignore_missing_images: true
